### PR TITLE
Fix memory leaks

### LINKED ISSUE #115: Fix memory leaks
**Description:**
Doing a static analysis or enabling sanitizers show that that is a large number of memory leaks in the LLVM codegen classes. Suggest that we fix these leaks using smart pointers.

**Suggested Labels:**
Priority/High, Type/Bug, Points/2

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by ruvi-d**
## Purpose
Refactor all classes to use pointers more judiciously. 

Resolves #115 
Not in scope : #158  

## Approach
* Avoid using pointers for class member
* Return object references instead of pointers when it can't be nullptr
* Use of const keyword to indicate and enforce immutability 
* Use of unique or shared pointers instead of raw pointers

### CODE REVIEW

**Comment by ruvi-d** [comment]
@ayonam kind reminder to review this PR

File: compiler/include/BasicBlock.h [hunk 1]
```diff
@@ -32,30 +32,33 @@ class Function;
 class TerminatorInsn;
 class NonTerminatorInsn;
 
-class BasicBlock : public PackageNode, public Debuggable, public Translatable {
+class BasicBlock : public Debuggable, public Translatable {
```
Comment (ayonam) [inline compiler/include/BasicBlock.h:35]: Why do we no longer derive from PackageNode?

File: compiler/include/ConstantLoad.h [hunk 2]
```diff
@@ -29,35 +30,21 @@ namespace nballerina {
...
-        int intValue;
-        double floatValue;
-        bool boolValue;
-        std::string *strValue;
-        value() {}
-        value(int x) : intValue(x) {}
-        value(float x) : floatValue(x) {}
-        value(bool x) : boolValue(x) {}
-        value(std::string *x) : strValue(x) {}
-    } val;
```
Comment (ayonam) [inline compiler/include/ConstantLoad.h:42]: Since only one value can be active at a time, why not have this as a union?  The different constructors for different value types can still be there and they could invoke the relevant constructor for value().

File: compiler/include/Function.h [hunk 3]
```diff
@@ -32,69 +35,67 @@ namespace nballerina {
...
 class FunctionParam;
-class Variable;
-class InvokableType;
-class RestParam;
+class InvocableType;
 class Type;
 class Package;
 
-class Function : public PackageNode, public Debuggable, public Translatable {
+class Function : public Debuggable, public Translatable {
```
Comment (ayonam) [inline compiler/include/Function.h:42]: Again here we don't derive from PackageNode. Shouldn't we be having the Package information with the Function?  We may need to access it for various reasons.  Just my thoughts.

File: compiler/include/FunctionCallInsn.h [hunk 4]
```diff
@@ -30,18 +30,14 @@ class FunctionCallInsn : public TerminatorInsn {
...
     std::string functionName;
     int argCount;
-    std::vector<Operand *> argsList;
+    std::vector<Operand> argsList;
 
   public:
     FunctionCallInsn() = delete;
-    FunctionCallInsn(bool funcVirtual, std::string _funcName, int argNumber, BasicBlock *nextBB, Operand *lhsOp,
-                     std::vector<Operand *> &fnArgs, BasicBlock *currentBB);
+    FunctionCallInsn(std::string _funcName, int argNumber, std::shared_ptr<BasicBlock> nextBB, const Operand &lhs,
```
Comment (ayonam) [inline compiler/include/FunctionCallInsn.h:37]: What was the relevance of funcVirtual earlier?  Why have we dropped it?  These were added to these classes basis the fields in the BIR.  So unless they are no longer relevant in the BIR, we should not be dropping them.

File: compiler/include/FunctionParam.h [hunk 5]
```diff
@@ -20,21 +20,22 @@
...
 
 class FunctionParam : public Operand {
   private:
-    Type *type;
+    Type type;
 
   public:
     FunctionParam() = delete;
-    FunctionParam(std::string name) : Operand(std::move(name), ARG_VAR_KIND), type(nullptr) {}
+    FunctionParam(Operand paramOp, Type type) : Operand(std::move(paramOp)), type(std::move(type)) {}
```
Comment (ayonam) [inline compiler/include/FunctionParam.h:35]: I'm assuming that the name of the operand has been captured while creating the paramOp.

File: compiler/include/Location.h [hunk 6]
```diff
@@ -26,21 +26,21 @@ namespace nballerina {
 class Location {
   private:
     std::string fileName;
-    const int sLine;
-    const int sCol;
-    const int eLine;
-    const int eCol;
+    int sLine;
```
Comment (ayonam) [inline compiler/include/Location.h:29]: Shouldn't these be const here?  We don't expect them to change, do we?  Besides there are no set methods either.

File: compiler/include/Package.h [hunk 7]
```diff
@@ -19,64 +19,73 @@
...
 
 class Package : public Translatable {
   private:
+    inline static const std::string BAL_NIL_VALUE = "bal_nil_value";
+    inline static const std::string STRING_TABLE_NAME = "__string_table_ptr";
     std::string org;
     std::string name;
     std::string version;
     std::string sourceFileName;
-    std::vector<Function *> functions;
```
Comment (ayonam) [inline compiler/include/Package.h:42]: I'm assuming that the pointers to the Function objects are being stored in the functionLookUp map and hence this vector is redundant.

File: compiler/include/Package.h [hunk 8]
```diff
@@ -19,64 +19,73 @@
...
-    llvm::StructType *boxType;
-    llvm::StringTableBuilder *strBuilder;
+    std::map<std::string, std::shared_ptr<Function>> functionLookUp;
+    std::unique_ptr<llvm::StructType> boxType;
+    std::unique_ptr<llvm::StringTableBuilder> strBuilder;
     std::map<std::string, std::vector<LLVMValueRef>> structElementStoreInst;
     std::map<std::string, LLVMValueRef> functionRefs;
+    std::vector<std::unique_ptr<llvm::GlobalVariable>> globalStringValues;
     void applyStringOffsetRelocations(LLVMModuleRef &modRef);
-    inline static const std::string BAL_NIL_VALUE = "bal_nil_value";
```
Comment (ayonam) [inline compiler/include/Package.h:51]: Are we now storing the NIL value elsewhere?

File: compiler/include/RestParam.h [hunk 9]
```diff
@@ -24,14 +24,9 @@
 namespace nballerina {
 
 class RestParam {
-  private:
-    std::string name;
-
```
Comment (ayonam) [inline compiler/include/RestParam.h:29]: Don't the RestParams have a name anymore?  I thought the BIR sent a name here.

File: compiler/include/TypeCastInsn.h [hunk 10]
```diff
@@ -30,15 +30,13 @@ class Operand;
 
 class TypeCastInsn : public NonTerminatorInsn {
   private:
-    Operand *rhsOp;
-    LLVMValueRef getIsSameTypeDeclaration(LLVMModuleRef &modRef, Package *pkg, LLVMValueRef lhsRef,
-                                          LLVMValueRef rhsRef);
```
Comment (ayonam) [inline compiler/include/TypeCastInsn.h:35]: In this function, are we not using the Package anymore?

File: compiler/include/Types.h [hunk 11]
```diff
@@ -83,29 +85,19 @@ class Type {
   private:
     TypeTag type;
     std::string name;
-    const int flags;
+    int flags;
```
Comment (ayonam) [inline compiler/include/Types.h:88]: Do we expect to change the flags here?  These are directly obtained from the BIR.  So I don't think we will be changing them once they are set.  Shouldn't this should remain a const?

File: compiler/include/interfaces/AbstractInstruction.h [hunk 12]
```diff
@@ -70,20 +71,22 @@ enum InstructionKind {
     INSTRUCTION_KIND_BINARY_BITWISE_UNSIGNED_RIGHT_SHIFT
 };
 
-class AbstractInstruction : public Debuggable, public PackageNode {
+class AbstractInstruction : public Debuggable {
```
Comment (ayonam) [inline compiler/include/interfaces/AbstractInstruction.h:74]: Again, why is the Package not made accessible to these classes?  There are times, when we may need it for the LLVM code generation.  I thought Package was the BIR synonym the LLVM Module.

**Review by ayonam — CHANGES_REQUESTED** [review]

File: compiler/codegen/InvokableType.cpp [hunk 13]
```diff
@@ -1,34 +0,0 @@
...
-
-InvokableType::InvokableType(std::vector<Type *> paramTy, Type *retTy)
-    : paramTypes(std::move(paramTy)), restType(nullptr), returnType(retTy) {}
-
-const Type *InvokableType::getReturnType() { return returnType; }
-const Type *InvokableType::getRestType() { return restType; }
-Type *InvokableType::getParamType(int i) { return paramTypes[i]; }
-size_t InvokableType::getParamTypeCount() { return paramTypes.size(); }
-
-} // namespace nballerina
```
[the remark this answers is not in the document]
Comment (ruvi-d) [reply compiler/codegen/InvokableType.cpp:34]: Renamed the class from `InvokableType` to `InvocableType`

File: compiler/codegen/Types.cpp [hunk 14]
```diff
@@ -44,9 +54,4 @@ const char *Type::getNameOfType(TypeTag typeTag) {
     }
 }
 
-MapTypeDecl::MapTypeDecl(TypeTag type, std::string name, int flags, TypeTag memberType)
-    : Type{type, std::move(name), flags}, memberType{memberType} {}
-
-TypeTag MapTypeDecl::getMemberTypeTag() { return memberType; }
-
```
[the remark this answers is not in the document]
Comment (ruvi-d) [reply compiler/codegen/Types.cpp:51]: Moved the one extra class member supported by MapTypeDecl (memberType) to the Type base class as an optional member. The overhead of introducing MapTypeDecl just to support one additional trivial member seemed unnecessary. If we had used MapTypeDecl, then we would have had to use heap allocated pointers to deal with Type objects and then incur extra overhead for the de-referencing.

File: compiler/include/BasicBlock.h (hunk 1 above)
Comment (ruvi-d) [reply compiler/include/BasicBlock.h:35]: The PackageNode interface only had a getPackage() method and that method implementation was moved to the respective classes. It was only used as a private method by their respective classes. Exposing this method as a interface's public method didn't net any benefit.

File: compiler/include/ConstantLoad.h (hunk 2 above)
Comment (ruvi-d) [reply compiler/include/ConstantLoad.h:42]: Yes, actually a std::variant (type safe version of union) would make sense here. Will update.

File: compiler/include/Function.h (hunk 3 above)
Comment (ruvi-d) [reply compiler/include/Function.h:42]: Commented here: https://github.com/ballerina-platform/nballerina/pull/180#discussion_r597385022

File: compiler/include/FunctionCallInsn.h (hunk 4 above)
Comment (ruvi-d) [reply compiler/include/FunctionCallInsn.h:37]: Currently when we are parsing BIR fields, we are leaving some unused and passing others to the CodeGen class constructors. But some of these fields were being unused in the CodeGen classes as well. So, to make things consistent and easily understand for future developers, I've removed all the unused params from class constructors and marked them as `unused` in the BIRReader. Then by looking at the BIRReader code you know exactly which fields are being used or ignored currently.

File: compiler/include/FunctionParam.h (hunk 5 above)
Comment (ruvi-d) [reply compiler/include/FunctionParam.h:35]: That's right

File: compiler/include/Package.h (hunk 7 above)
Comment (ruvi-d) [reply compiler/include/Package.h:42]: Yes

File: compiler/include/Location.h (hunk 6 above)
Comment (ruvi-d) [reply compiler/include/Location.h:29]: Using const member variables is discouraged since it makes it non trivial to copy and thus has adverse side effects like preventing moves. The recommendation I've seen is to keep member variables non-const and remove the setter methods instead.
https://www.reddit.com/r/cpp/comments/8wbeom/coding_guideline_avoid_const_member_variables/

File: compiler/include/Package.h (hunk 8 above)
Comment (ruvi-d) [reply compiler/include/Package.h:51]: It's just been moved a few lines above. The diff isn't showing that.

File: compiler/include/RestParam.h (hunk 9 above)
Comment (ruvi-d) [reply compiler/include/RestParam.h:29]: This change was also done for the same reason as mentioned previously about removing unused fields. 
https://github.com/ballerina-platform/nballerina/pull/180#discussion_r597387522

File: compiler/include/TypeCastInsn.h (hunk 10 above)
Comment (ruvi-d) [reply compiler/include/TypeCastInsn.h:35]: A reference to the parent package is already available to this class object. So unless we make this method Static, there was no need to pass a redundant package pointer

File: compiler/include/Types.h (hunk 11 above)
Comment (ruvi-d) [reply compiler/include/Types.h:88]: I am following the previously mentioned guidelines about const member variables
https://github.com/ballerina-platform/nballerina/pull/180#discussion_r597389997

File: compiler/include/interfaces/AbstractInstruction.h (hunk 12 above)
Comment (ruvi-d) [reply compiler/include/interfaces/AbstractInstruction.h:74]: Answered in https://github.com/ballerina-platform/nballerina/pull/180#discussion_r597385022

File: compiler/include/ConstantLoad.h (hunk 2 above)
Comment (ruvi-d) [reply compiler/include/ConstantLoad.h:42]: Push an update addressing this

**Comment by ruvi-d** [comment]
@ayonam I've replied to your comments. Please check.

**Comment by ruvi-d** [comment]
Rebased with master

File: compiler/codegen/Types.cpp (hunk 14 above)
[the remark this answers is not in the document]
Comment (ayonam) [reply compiler/codegen/Types.cpp:53]: Okay.  Got it.  That's fine.

File: compiler/include/BasicBlock.h (hunk 1 above)
Comment (ayonam) [reply compiler/include/BasicBlock.h:35]: Accepted.

File: compiler/include/FunctionCallInsn.h (hunk 4 above)
Comment (ayonam) [reply compiler/include/FunctionCallInsn.h:37]: That sounds reasonable.

File: compiler/include/RestParam.h (hunk 9 above)
Comment (ayonam) [reply compiler/include/RestParam.h:29]: Got it.  Thanks,

**Review by ayonam — APPROVED** [review]

**Review by KavinduZoysa — APPROVED** [review]
