### PR TITLE
Array type support for float, boolean and string types

### LINKED ISSUE #136: Array type support for float, boolean and string types
**Description:**
Current implementation supports only int arrays at rust side and translation side.
We need to support float, boolean and string types.
   string, float, boolean 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
#124

### PR DESCRIPTION
**Pull request by ramakotareddy**
Generic type array support (int, float, boolean and String)
    Added test cases for newly  added Array types.
    Fix all review comments #182 
    
Resolves #136
 Fix all review comments #182

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

**Comment by ramakotareddy** [comment]
Fix all review comments from #182  and created separated issue #218 for Rust related comments and shubham will address these rust related comments.

**Comment by ruvi-d** [comment]
Need to address : https://github.com/ballerina-platform/nballerina/pull/182#discussion_r599536591

File: compiler/codegen/Types.cpp [hunk 1]
```diff
@@ -23,8 +23,10 @@ namespace nballerina {
 Type::Type(TypeTag type, std::string namep, int flagsp, TypeTag memberType)
     : type(type), name(std::move(namep)), flags(flagsp), memberType(memberType) {}
 
-Type::Type(TypeTag type, std::string namep, int flagsp)
-    : type(type), name(std::move(namep)), flags(flagsp) {}
+Type::Type(TypeTag type, std::string namep, int flagsp) : type(type), name(std::move(namep)), flags(flagsp) {}
+
+Type::Type(TypeTag type, std::string namep, int flagsp, TypeTag memberType, int size, int state)
+    : type(type), name(std::move(namep)), flags(flagsp), memberType(memberType), size(size), state(state) {}
```
Comment (ruvi-d) [inline compiler/codegen/Types.cpp:29]: I think I mentioned this previously. We shouldn't be extending classes like this so support different variations. Shall we define structures to each new type and store them as std::variant as mentioned previously?
Here is an example: https://github.com/ballerina-platform/nballerina/blob/265df02e96b91953ca371f5b7a896d37ee4cfba6/compiler/include/MapInsns.h#L58
This is a bit more background about the approach: https://youtu.be/ojZbFIQSdl8?t=929

File: runtime/src/lib.rs [hunk 2]
```diff
@@ -114,19 +114,43 @@ pub extern "C" fn print_str(val: *const c_char) {
 }
 
 #[no_mangle]
-pub extern "C" fn new_int_array(size: i32) -> *mut Vec<*mut i32> {
-    let mut size_t = size;
-    if size < 0 {
-        size_t = 8;
-    }
+pub extern "C" fn array_init_int(size: i32) -> *mut Vec<*mut i32> {
```
Comment (ruvi-d) [inline runtime/src/lib.rs:117]: Since all array_init_ functions have effectively the same method signature, can we combine them into one like:
`array_int(size: i32, type: *const c_char)`
Then we can have just one function call for all the types (will work for both primitive and reference types). We can match the passed `type` c-string and create the correct type of vector from the Rust side.
WDYT?

File: runtime/src/lib.rs [hunk 3]
```diff
@@ -138,14 +162,117 @@ pub extern "C" fn int_array_store(arr_ptr: *mut Vec<*mut i32>, n: i32, ref_ptr:
...
     let n_size = n as usize;
     let return_val = arr[n_size];
     mem::forget(arr);
     return return_val;
 }
 
+#[no_mangle]
+pub extern "C" fn array_store_float(arr_ptr: *mut Vec<*mut f32>, n: i32, ref_ptr: *mut f32) {
+    let mut arr = unsafe { Box::from_raw(arr_ptr) };
+    let n_size = n as usize;
```
Comment (ruvi-d) [inline runtime/src/lib.rs:176]: Should be named index, not n_size
Repeat for other functions too.

File: runtime/src/lib.rs [hunk 4]
```diff
@@ -138,14 +162,117 @@ pub extern "C" fn int_array_store(arr_ptr: *mut Vec<*mut i32>, n: i32, ref_ptr:
...
+    }
+    arr[n_size] = ref_ptr;
+    mem::forget(arr);
+}
+
+#[no_mangle]
+pub extern "C" fn array_load_float(arr_ptr: *mut Vec<*mut f32>, n: i32) -> *mut f32 {
+    let arr = unsafe { Box::from_raw(arr_ptr)};
+    let n_size = n as usize;
+    let return_val = arr[n_size];
```
Comment (ruvi-d) [inline runtime/src/lib.rs:189]: Don't we need to check whether array access is out of bounds?

File: test/array/booleanArrayLoadAndStore.bal [hunk 5]
```diff
@@ -0,0 +1,17 @@
...
+
+public function print_str(string val) = external;
+
+public function printu32(int val) = external;
+
+public function main() {
+    boolean[5] arr4 = [];
+    arr4[0] = true;
+    any b1 = arr4[0];
+    boolean b = <boolean>b1;
```
Comment (ruvi-d) [inline test/array/booleanArrayLoadAndStore.bal:11]: Let's only do load/store in this test. Write separate tests for any casting, function params, global variables for key and value, etc..  

For this load and store test, store more than one value

File: test/array/stringArrayLoadAndStore.bal [hunk 6]
```diff
@@ -0,0 +1,16 @@
...
+public function bar(any l) returns string {
+    string g = <string>l;
+    return g;
+}
+public function main() {
+    string[5] arr4 = [];
+    arr4[0] = "Hello";
+    string b = bar(arr4[0]);
+    print_str("RESULT=");
+    print_str(b);
```
Comment (ruvi-d) [inline test/array/stringArrayLoadAndStore.bal:14]: Let's only do load/store in this test. Write separate tests for any casting, function params, global variables for key and value, etc..  

For this load and store test, store more than one value. like
```
arr4[0] = "Hello";
arr4[2] = " World";
string b = arr4[0];
string c = arr4[2];
print_str("RESULT=");
print_str(b);
print_str(c);
```

**Comment by KavinduZoysa** [comment]
It seems we need to have more test cases, such as
1. arrays as global var
2. array in function return
3. array in function arg

Please consider different cases as much as possible.

**Review by ruvi-d — CHANGES_REQUESTED** [review]

**Comment by ruvi-d** [comment]
> It seems we need to have more test cases, such as
> 
> 1. arrays as global var
> 2. array in function return
> 3. array in function arg
> 
> Please consider different cases as much as possible.

+1 
You can more easily identify the missing test cases if you follow the naming convention from #213 and refer the tests from the other types.

File: compiler/codegen/ArrayInsns.cpp [hunk 7]
```diff
@@ -32,15 +34,20 @@ ArrayInsn::ArrayInsn(const Operand &lhs, std::shared_ptr<BasicBlock> currentBB,
...
 
 LLVMValueRef ArrayInsn::getArrayInitDeclaration(LLVMModuleRef &modRef) {
-    const char *newIntArrayChar = "new_int_array";
-    LLVMValueRef addedFuncRef = getPackageRef().getFunctionRef(newIntArrayChar);
+    auto lhsVar = getFunctionRef().getLocalOrGlobalVariable(getLhsOperand());
+    assert(lhsVar.has_value());
+    const auto &arrayType = lhsVar->getType();
+    TypeTag memberTypeTag = arrayType.getMemberTypeTag();
+    const string typeStr(Type::getNameOfType(memberTypeTag));
+    const string arrayTypeFuncName = "array_init_" + typeStr;
```
[the remark this answers is not in the document]
Comment (ruvi-d) [reply compiler/codegen/ArrayInsns.cpp:42]: We generally won't to avoid named variables that are only used once.

File: compiler/codegen/ArrayInsns.cpp [hunk 8]
```diff
@@ -60,55 +67,64 @@ ArrayLoadInsn::ArrayLoadInsn(const Operand &lhs, std::shared_ptr<BasicBlock> cur
...
+    addedFuncRef = LLVMAddFunction(modRef, arrayTypeFuncName.c_str(), funcType);
+    getPackageMutableRef().addFunctionRef(arrayTypeFuncName, addedFuncRef);
     return addedFuncRef;
 }
 
 void ArrayLoadInsn::translate(LLVMModuleRef &modRef) {
     const auto &funcObj = getFunctionRef();
     LLVMBuilderRef builder = funcObj.getLLVMBuilder();
-    LLVMValueRef ArrayLoadFunc = getArrayLoadDeclaration(modRef);
+    assert(funcObj.getLocalOrGlobalVariable(getLhsOperand())->getType().getTypeTag());
```
[the remark this answers is not in the document]
Comment (ramakotareddy) [reply compiler/codegen/ArrayInsns.cpp]: Fixed

File: compiler/codegen/ArrayInsns.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (ramakotareddy) [reply compiler/codegen/ArrayInsns.cpp]: Fixed

File: compiler/codegen/ArrayInsns.cpp [hunk 9]
```diff
@@ -60,55 +67,64 @@ ArrayLoadInsn::ArrayLoadInsn(const Operand &lhs, std::shared_ptr<BasicBlock> cur
...
 
-LLVMValueRef ArrayLoadInsn::getArrayLoadDeclaration(LLVMModuleRef &modRef) {
-    const char *intArrayLoadChar = "int_array_load";
-    LLVMValueRef addedFuncRef = getPackageRef().getFunctionRef(intArrayLoadChar);
+LLVMValueRef ArrayLoadInsn::getArrayLoadDeclaration(LLVMModuleRef &modRef, TypeTag lhsOpTypeTag) {
+    const string typeStr(Type::getNameOfType(lhsOpTypeTag));
+    const string arrayTypeFuncName = "array_load_" + typeStr;
+    Type lhsType = getFunctionRef().getLocalOrGlobalVariable(getLhsOperand())->getType();
+    LLVMTypeRef funcRetType = LLVMPointerType(getPackageMutableRef().getLLVMTypeOfType(lhsType), 0);
+    LLVMValueRef addedFuncRef = getPackageMutableRef().getFunctionRef(arrayTypeFuncName);
```
[the remark this answers is not in the document]
Comment (ramakotareddy) [reply compiler/codegen/ArrayInsns.cpp]: Fixed

File: compiler/codegen/ArrayInsns.cpp [hunk 10]
```diff
@@ -60,55 +67,64 @@ ArrayLoadInsn::ArrayLoadInsn(const Operand &lhs, std::shared_ptr<BasicBlock> cur
...
+    getPackageMutableRef().addFunctionRef(arrayTypeFuncName, addedFuncRef);
     return addedFuncRef;
 }
 
 void ArrayLoadInsn::translate(LLVMModuleRef &modRef) {
     const auto &funcObj = getFunctionRef();
     LLVMBuilderRef builder = funcObj.getLLVMBuilder();
-    LLVMValueRef ArrayLoadFunc = getArrayLoadDeclaration(modRef);
+    assert(funcObj.getLocalOrGlobalVariable(getLhsOperand())->getType().getTypeTag());
+    TypeTag lhsOpTypeTag = (TypeTag)(funcObj.getLocalOrGlobalVariable(getLhsOperand())->getType().getTypeTag());
```
[the remark this answers is not in the document]
Comment (ramakotareddy) [reply compiler/codegen/ArrayInsns.cpp]: Fixed

File: runtime/src/lib.rs (hunk 3 above)
Comment (ramakotareddy) [reply runtime/src/lib.rs]: Fixed

**Comment by ramakotareddy** [comment]
Add support for array of arrays (multi dimensional arrays) int type.

**Comment by ramakotareddy** [comment]
Add Support of Array of Arrays with Two dimensional array.
Added test cases with two dimensional load and store. will add more test cases with n dimensional and with array type cast.

**Comment by ruvi-d** [comment]
> Add Support of Array of Arrays with Two dimensional array.
> Added test cases with two dimensional load and store. will add more test cases with n dimensional and with array type cast.

This PR title is "Array type support for float, boolean and string and array of arrays".. 
Are you sure you want to merge "Array of Arrays and Union types" with this PR? 
I would have thought that separate PRs would make sense, because we haven't resolved all the issues from the first review. If you keep adding commits with new functionality, we can't verify that you are fixing the review comments without having to do a complete PR review again.

**Comment by ramakotareddy** [comment]
Added test cases.

File: test/array/stringArrayLoadAndStore.bal (hunk 6 above)
Comment (ramakotareddy) [reply test/array/stringArrayLoadAndStore.bal]: Fixed

File: test/array/booleanArrayLoadAndStore.bal (hunk 5 above)
Comment (ramakotareddy) [reply test/array/booleanArrayLoadAndStore.bal]: Fixed

File: test/array/string_array_with_any_typecast.bal [hunk 11]
```diff
@@ -0,0 +1,16 @@
...
+
+public function print_string(string val) = external;
+
+public function bar(any l) returns string {
+    string g = <string>l;
+    return g;
+}
+public function main() {
+    string[5] arr4 = [];
+    arr4[0] = "Hello";
```
Comment (ruvi-d) [inline test/array/string_array_with_any_typecast.bal:11]: Since this is an array, let's initialize at least two values like:
```
arr4[1] = " World";
```
And print both values. Otherwise this test would pass even if string[] = string.

File: test/array/function_call_string_array.bal [hunk 12]
```diff
@@ -0,0 +1,19 @@
+// RUN: "%testRunScript" %s %nballerinacc "%java_path" | filecheck %s
+
+public function print_string(string val) = external;
+
+public function printu32(int val) = external;
```
Comment (ruvi-d) [inline test/array/function_call_string_array.bal:5]: printu32 not used

File: test/array/function_call_boolean_array.bal [hunk 13]
```diff
@@ -0,0 +1,21 @@
...
+
+public function test(boolean[] a) returns boolean {
+    boolean c = a[1];
+    return c;
+}
+public function main() {
+    boolean[4] arr1 = [];
+    arr1[0] = true;
+    arr1[1] = false;
+    if (!test(arr1)) {
```
Comment (ruvi-d) [inline test/array/function_call_boolean_array.bal:15]: don't use `!` because of #212

File: test/array/boolean_array_with_any_typecast.bal [hunk 14]
```diff
@@ -0,0 +1,17 @@
+// RUN: "%testRunScript" %s %nballerinacc "%java_path" | filecheck %s
+
+public function print_string(string val) = external;
+
+public function printu32(int val) = external;
+
+public function main() {
+    boolean[5] arr4 = [];
+    arr4[0] = true;
```
Comment (ruvi-d) [inline test/array/boolean_array_with_any_typecast.bal:9]: Since this is an array, let's initialize at least two values mentioned previously. But be aware of #199

File: test/array/boolean_array_global_boolean.bal [hunk 15]
```diff
@@ -0,0 +1,17 @@
+// RUN: "%testRunScript" %s %nballerinacc "%java_path" | filecheck %s
+
+public function print_string(string val) = external;
+
+public function printu32(int val) = external;
+
+boolean[5] arr4 = [];
+public function main() {
+    arr4 = [];
+    arr4[0] = true;
```
Comment (ruvi-d) [inline test/array/boolean_array_global_boolean.bal:10]: As mentioned, let's initialize at least two values

**Review by ruvi-d — CHANGES_REQUESTED** [review]

File: compiler/codegen/Types.cpp [hunk 16]
```diff
@@ -20,17 +20,23 @@
 
 namespace nballerina {
 
-Type::Type(TypeTag type, std::string namep, TypeTag memberType)
-    : type(type), name(std::move(namep)), memberType(memberType) {}
+Type::Type(TypeTag type, std::string namep) : type(type), name(std::move(namep))  {}
 
-Type::Type(TypeTag type, std::string namep) : type(type), name(std::move(namep)) {}
+Type::Type(TypeTag type, std::string namep, ArrayType arrayType)
+    : type(type), name(std::move(namep)), typeInfo(arrayType) {}
```
Comment (ruvi-d) [inline compiler/codegen/Types.cpp:26]: Doesn't the static analyzer recommend to move the typeInfo?

File: runtime/src/lib.rs (hunk 2 above)
Comment (ruvi-d) [reply runtime/src/lib.rs:142]: Create an issue for this if you are not gonna handle it in this PR

File: runtime/src/lib.rs [hunk 17]
```diff
@@ -139,38 +139,165 @@ pub extern "C" fn printf32(num32: f32) {
...
-    let n_size = n as usize;
-    let return_val = arr[n_size];
+    let index_n = index as usize;
+    let return_val = arr[index_n];
+    mem::forget(arr);
+    return return_val;
+}
+
+#[no_mangle]
+pub extern "C" fn array_store_float(arr_ptr: *mut Vec<*mut f32>, index: i32, ref_ptr: *mut f32) {
```
Comment (ruvi-d) [inline runtime/src/lib.rs:199]: @ramakotareddy : Why are we are still passing values by reference for float, bool and int?

File: test/array/function_call_boolean_array.bal (hunk 13 above)
Comment (ramakotareddy) [reply test/array/function_call_boolean_array.bal:15]: Ruvi,  We don't have print_boolean also. How can we check the boolean values? Please suggest

**Review by ruvi-d — CHANGES_REQUESTED** [review]

File: runtime/src/lib.rs (hunk 17 above)
Comment (ramakotareddy) [reply runtime/src/lib.rs:199]: In the new issue #218, will fix this. We need to change few things in Codegen side also.

File: runtime/src/lib.rs (hunk 4 above)
Comment (ruvi-d) [reply runtime/src/lib.rs]: This has not been addressed

**Comment by ruvi-d** [comment]
Other open issues: 
https://github.com/ballerina-platform/nballerina/pull/219#discussion_r602891627
https://github.com/ballerina-platform/nballerina/pull/219#discussion_r602890915

Please address all open issues before requesting another review

File: runtime/src/lib.rs (hunk 2 above)
Comment (ramakotareddy) [reply runtime/src/lib.rs:142]: Combine the array init functions into one #222

File: test/array/boolean_array_global_boolean.bal (hunk 15 above)
Comment (ramakotareddy) [reply test/array/boolean_array_global_boolean.bal:10]: Fixed

File: test/array/boolean_array_with_any_typecast.bal (hunk 14 above)
Comment (ramakotareddy) [reply test/array/boolean_array_with_any_typecast.bal:9]: Fixed

File: test/array/function_call_boolean_array.bal (hunk 13 above)
Comment (ramakotareddy) [reply test/array/function_call_boolean_array.bal]: Fixed

File: test/array/function_call_string_array.bal (hunk 12 above)
Comment (ramakotareddy) [reply test/array/function_call_string_array.bal]: Fixed

File: test/array/string_array_with_any_typecast.bal (hunk 11 above)
Comment (ramakotareddy) [reply test/array/string_array_with_any_typecast.bal:11]: Fixed

File: runtime/src/lib.rs (hunk 17 above)
Comment (ramakotareddy) [reply runtime/src/lib.rs:199]: @ruvi-d , If i pass by value, printing int number as some garbage value instead of some number in my case. we need to debug deep and fix this issue. I will address this issue in #218 issue.

File: compiler/codegen/Types.cpp (hunk 16 above)
Comment (ramakotareddy) [reply compiler/codegen/Types.cpp:26]: @ruvi-d , i got only three warnings related to constructor parameter names from Type and i have fixed those. i didn't get any recommendation/warning from static analyzer regarding move the typeInfo.

File: runtime/src/lib.rs (hunk 4 above)
Comment (ramakotareddy) [reply runtime/src/lib.rs]: Fixed

File: runtime/src/lib.rs (hunk 17 above)
Comment (ruvi-d) [reply runtime/src/lib.rs:201]: @ramakotareddy : can you clean up the description in #218 and just list in bullet form the pending items? i.e. without only the links. It's important to list them out because all of them don't have the same priority. I believe that we discussed that things like refactoring shapinfo class to use variants is low priority. 
This pass by reference issue I think is high priority and should be fixed before array of arrays.

Comment (ramakotareddy) [reply runtime/src/lib.rs:201]: @ruvi-d , from the #218 issue i have updated the description and those two links are pointed to same issue.(pass by value) and we already addressed std::variant issue.

File: runtime/src/lib.rs [hunk 18]
```diff
@@ -139,38 +139,173 @@ pub extern "C" fn printf32(num32: f32) {
...
+    arr[index_n] = ref_ptr;
+    mem::forget(arr);
+}
+
+#[no_mangle]
+pub extern "C" fn array_load_float(arr_ptr: *mut Vec<*mut f32>, index: i32) -> *mut f32 {
+    let arr = unsafe { Box::from_raw(arr_ptr)};
+    let index_n = index as usize;
+    // check the out of bounds.
+    assert!(arr.len() > index_n);
```
Comment (ruvi-d) [inline runtime/src/lib.rs:217]: We need a test that covers this. Please create a task and link it with #181

**Review by ruvi-d — CHANGES_REQUESTED** [review]

File: runtime/src/lib.rs (hunk 18 above)
Comment (ramakotareddy) [reply runtime/src/lib.rs:217]: Created Ruvi, Create test case of Array out of bound Access Abort functionality #223

**Review by ruvi-d — APPROVED** [review]

**Review by Kishanthan — APPROVED** [review]
