### PR TITLE
Demangle function name at runtime

### LINKED ISSUE #458: Demangle function names in backtraces
When a panic prints out a function name, it should demangle it.

Mangling is described here: https://github.com/ballerina-platform/nballerina/issues/448#issuecomment-919844131

### PR DESCRIPTION
**Pull request by KavinduZoysa**
## Purpose
Fixes #458

### CODE REVIEW

**Comment by KavinduZoysa** [comment]
Calling _bal_print_mangled_name is not implemented yet, because it depends on #432

File: runtime/tests/demangle.c [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+    "_.io:println\n",
+    "2.io:println\n",
+    "foo_bar.io:println\n",
+    "foo_bar._bar.io:println\n",
+    "foo_bar.2bar.io:println\n",
+    "foo_bar.2bar._io:println\n",
+    "foo_bar.2bar.io:_println\n",
+    "foo_bar.2bar.io:_3println\n",
+    "foo_bar.2bar.new_nballerina_module:_3println\n",
+    "foo_bar.2bar.new_ballerina_module:_3println\n"
```
Comment (manuranga) [inline runtime/tests/demangle.c]: Is it possible to avoid `\n`on each case, and to just check it in the test?

File: runtime/error.c [hunk 2]
```diff
@@ -181,3 +187,83 @@ TaggedPtr BAL_LANG_ERROR_NAME(message)(TaggedPtr error) {
...
+static int getOrgNameOffset(const char *mangledName) {
+    // Offset starts from '_B'
+    int offset = 2;
+    if (mangledName[offset] == 'b') {
+        offset++;
+    }
+    return offset + getzQualifierOffset(mangledName + offset);
+}
+
+static int getzQualifierOffset(const char *mangledName) {
```
Comment (manuranga) [inline runtime/error.c]: Why `z` in `getz` ?

File: runtime/tests/demangle.c (hunk 1 above)
Comment (KavinduZoysa) [reply runtime/tests/demangle.c]: Yes, we can do that. The reason to use '\n' is to indicate the end of the demangled name.

File: runtime/error.c (hunk 2 above)
Comment (KavinduZoysa) [reply runtime/error.c]: Actually I am using the keywords used in https://github.com/ballerina-platform/nballerina/issues/448#issuecomment-919844131

File: runtime/error.c [hunk 3]
```diff
@@ -181,3 +187,83 @@ TaggedPtr BAL_LANG_ERROR_NAME(message)(TaggedPtr error) {
     ErrorPtr ep = taggedToPtr(error);
     return ep->message;
 }
+
+void _bal_print_mangled_name(const char *mangledName, FILE *fp) {
```
Comment (jclark) [inline runtime/error.c:265]: This needs to written so that it has well-defined behaviour when passed arbitrary function names.

File: runtime/error.c [hunk 4]
```diff
@@ -181,3 +187,83 @@ TaggedPtr BAL_LANG_ERROR_NAME(message)(TaggedPtr error) {
...
+    // If mangled name starts from _B_, the identifier is non-public
+    if (mangledName[2] == '_') {
```
Comment (jclark) [inline runtime/error.c]: This code makes me sad. First, you must not assume that the first two chars are `_B`. More importantly, you must not assume that mangledName has length > 1.

File: runtime/error.c [hunk 5]
```diff
@@ -181,3 +187,83 @@ TaggedPtr BAL_LANG_ERROR_NAME(message)(TaggedPtr error) {
...
+    // The org-name is not considered as a part of function name in backtrace.
+    int initialOffset = getOrgNameOffset(mangledName);
+
+    // Make sure parsing starts from the first character of
+    // nqual, local-name or mod-name
+    bool isFirstQualifier = true;
+    printModuleName(mangledName + initialOffset, &isFirstQualifier, fp);
+}
+
+static int getOrgNameOffset(const char *mangledName) {
```
Comment (jclark) [inline runtime/error.c]: This is all soooo ugly.

File: runtime/tests/demangle.c (hunk 1 above)
Comment (manuranga) [reply runtime/tests/demangle.c]: C strings do end in `\0` automatically, so why do we need another maker ?

File: runtime/error.c (hunk 2 above)
Comment (manuranga) [reply runtime/error.c]: Correct camlCase encoding of that would be `getZQualifierOffset`.

Comment (KavinduZoysa) [reply runtime/error.c]: Changed

File: runtime/error.c (hunk 3 above)
Comment (KavinduZoysa) [reply runtime/error.c:265]: Changed

File: runtime/error.c (hunk 4 above)
Comment (KavinduZoysa) [reply runtime/error.c]: Fixed

File: runtime/tests/demangle.c (hunk 1 above)
Comment (KavinduZoysa) [reply runtime/tests/demangle.c]: Yes, that is correct. When printing to an output file, I am adding a new line. That is why I am checking the new line. But removed the new line and checking the end of line in the test now.
Fixed

File: runtime/tests/demangle.c [hunk 6]
```diff
@@ -0,0 +1,100 @@
+#include "../balrt.h"
+#include "../hash.h"
+#include <stdio.h>
+#include <assert.h>
+
+#define NAMES_COUNT 28
+
+HASH_DEFINE_KEY;
+
+const char input[NAMES_COUNT][60] = {
```
Comment (manuranga) [inline runtime/tests/demangle.c]: I think it's better to have
```C
typedef struct {
    char subject[60];
    char expected[60];
} DemangleTestCase;

static const struct DemangleTestCase tests[] = {
    { "_Bb02ioprintln", "io:println" },
    ...
};
```

File: runtime/error.c [hunk 7]
```diff
@@ -17,6 +17,13 @@
 #define EXCEEDS_MAX_PC_COUNT -3
 #define OUT_OF_MEMORY -4
 
+#define NON_PUBLIC_SYMBOL_PREFIX "_B_"
+#define NON_PUBLIC_SYMBOL_PREFIX_LENGTH strlen(NON_PUBLIC_SYMBOL_PREFIX)
```
Comment (manuranga) [inline runtime/error.c]: Hopefully clang optimize this to a constant. @KavinduZoysa please verify.

File: runtime/tests/demangle.c (hunk 6 above)
Comment (KavinduZoysa) [reply runtime/tests/demangle.c]: Changed

File: runtime/error.c (hunk 7 above)
Comment (KavinduZoysa) [reply runtime/error.c]: Yes, it is optimized to a constant.

File: runtime/error.c [hunk 8]
```diff
@@ -17,6 +17,13 @@
 #define EXCEEDS_MAX_PC_COUNT -3
 #define OUT_OF_MEMORY -4
 
+#define PUBLIC_BALLERINA_NAME 1
```
Comment (jclark) [inline runtime/error.c]: Use a sensible set of numbers. Those were just the numbers in my list of possible cases.

File: runtime/error.c [hunk 9]
```diff
@@ -181,3 +193,113 @@ TaggedPtr BAL_LANG_ERROR_NAME(message)(TaggedPtr error) {
...
+    if (*name[0] == '_') {
+        *name = *name + 1;
+        nChars++;
+    }
+    *pp = *pp + nRead + nChars;
+    return true;
+}
+
+static void printUpto(const char *end, const char *start, FILE *fp) {
+    while (start < end) {
```
Comment (jclark) [inline runtime/error.c]: This can be a single call to fwrite.

File: runtime/error.c [hunk 10]
```diff
@@ -181,3 +193,113 @@ TaggedPtr BAL_LANG_ERROR_NAME(message)(TaggedPtr error) {
...
+    int nRead;
+    if (sscanf(*pp, "%ld%n", &nChars, &nRead) <= 0) {
+        return false;
+    }
+    *name = *pp + nRead;
+    if (*name[0] == '_') {
+        *name = *name + 1;
+        nChars++;
+    }
+    *pp = *pp + nRead + nChars;
```
Comment (jclark) [inline runtime/error.c]: You need to check that pp + nRead does not go past the terminating '\0' of the string. There is also a potential integer overflow

File: runtime/error.c [hunk 11]
```diff
@@ -181,3 +193,113 @@ TaggedPtr BAL_LANG_ERROR_NAME(message)(TaggedPtr error) {
...
+    return true;
+}
+
+static void printUpto(const char *end, const char *start, FILE *fp) {
```
Comment (jclark) [inline runtime/error.c]: First argument should be start; second argument should be a size_t length.  Call it printChars or something like that.

**Review by jclark — CHANGES_REQUESTED** [review]

File: runtime/error.c (hunk 11 above)
Comment (KavinduZoysa) [reply runtime/error.c]: Removed this method because this can be done a single line of code as suggested.

File: runtime/error.c (hunk 10 above)
Comment (KavinduZoysa) [reply runtime/error.c]: Fixed

File: runtime/error.c (hunk 9 above)
Comment (KavinduZoysa) [reply runtime/error.c]: Used `fwrite` instead of this whole method

File: runtime/error.c (hunk 8 above)
Comment (KavinduZoysa) [reply runtime/error.c]: Changed.

File: runtime/error.c [hunk 12]
```diff
@@ -181,3 +194,115 @@ TaggedPtr BAL_LANG_ERROR_NAME(message)(TaggedPtr error) {
...
+    }
+    if (nRead > MAX_DEMANGLING_DECIMAL_LENGTH) {
+        return false;
+    }
+    *name = *pp + nRead;
+    if (*name[0] == '_') {
+        *name = *name + 1;
+        nChars++;
+    }
+    for (int i = 0; i < nRead + nChars; i++) {
```
Comment (jclark) [inline runtime/error.c]: const char *p = name;

Then increment p and decrement nChars.

File: runtime/error.c [hunk 13]
```diff
@@ -181,3 +194,115 @@ TaggedPtr BAL_LANG_ERROR_NAME(message)(TaggedPtr error) {
...
+    return demangleModules(mangledModules, fp);
+}
+
+static bool demangleCountedName(const char **pp, const char **name) {
+    long nChars;
+    int nRead;
+    if (sscanf(*pp, "%ld%n", &nChars, &nRead) <= 0) {
+        return false;
+    }
+    if (nRead > MAX_DEMANGLING_DECIMAL_LENGTH) {
```
Comment (jclark) [inline runtime/error.c]: Why do we need this?

File: runtime/error.c [hunk 14]
```diff
@@ -181,3 +194,115 @@ TaggedPtr BAL_LANG_ERROR_NAME(message)(TaggedPtr error) {
...
+    }
+
+    bool ballerinaOrg = false; 
+    if (mangledName[0] == 'b') {
+        ballerinaOrg = true;
+        mangledName++;
+    }
+
+    const char *org;
+    if (mangledName[0] == '0') {
```
Comment (jclark) [inline runtime/error.c:299]: Don't need to special case this. You will just end up with an empty org (i.e. *org == '\0')

File: runtime/error.c [hunk 15]
```diff
@@ -181,3 +194,115 @@ TaggedPtr BAL_LANG_ERROR_NAME(message)(TaggedPtr error) {
...
+            return _B_NON_BALLERINA_NAME;
+        }
+    }
+    if (fp != NULL) {
+        bool haveOrg = false;
+        if (ballerinaOrg) {
+            fputs("ballerina", fp);
+            haveOrg = true;
+        }
+        if (org != NULL) {
```
Comment (jclark) [inline runtime/error.c:314]: if (*org != '\0)

**Review by jclark — CHANGES_REQUESTED** [review]

File: runtime/error.c (hunk 14 above)
Comment (KavinduZoysa) [reply runtime/error.c:299]: We need this for a case like `_Bb02ioprintln`. If we pass without checking '0' to `demangleCountedName` function, it reads `02` together.

File: runtime/error.c (hunk 13 above)
Comment (KavinduZoysa) [reply runtime/error.c]: I did this, because there was a potential integer overflow as mentioned above. Now we are not doing an addition like `nRead + nChars` we can remove this.

File: runtime/error.c (hunk 12 above)
Comment (KavinduZoysa) [reply runtime/error.c]: Fixed

File: runtime/error.c (hunk 14 above)
Comment (jclark) [reply runtime/error.c:299]: OK. Good point!

File: runtime/error.c [hunk 16]
```diff
@@ -250,3 +263,116 @@ TaggedPtr BAL_LANG_ERROR_NAME(message)(TaggedPtr error) {
...
+    return demangleModules(mangledModules, fp);
+}
+
+static bool demangleCountedName(const char **pp, const char **name) {
+    long nChars;
+    int nRead;
+    if (sscanf(*pp, "%ld%n", &nChars, &nRead) <= 0) {
+        return false;
+    }
+    if (nRead > MAX_DEMANGLING_DECIMAL_LENGTH) {
```
Comment (jclark) [inline runtime/error.c]: You don't need this.

File: runtime/error.c [hunk 17]
```diff
@@ -18,6 +18,15 @@
 #define EXCEEDS_MAX_PC_COUNT -3
 #define OUT_OF_MEMORY -4
 
+#define PUBLIC_BALLERINA_NAME 1
+#define NON_PUBLIC_BALLERINA_NAME 2
+#define NON_BALLERINA_NAME -1
+#define _B_NON_BALLERINA_NAME -2
+
+#define MAX_DEMANGLING_DECIMAL_LENGTH 4
```
Comment (jclark) [inline runtime/error.c]: Don't need this.

File: runtime/error.c [hunk 18]
```diff
@@ -18,6 +18,15 @@
 #define EXCEEDS_MAX_PC_COUNT -3
 #define OUT_OF_MEMORY -4
 
+#define PUBLIC_BALLERINA_NAME 1
```
Comment (jclark) [inline runtime/error.c]: These numbers seem fairly random to me. Simpler just to make DemangleResult be an enum.

**Review by jclark — CHANGES_REQUESTED** [review]

File: runtime/error.c (hunk 16 above)
Comment (KavinduZoysa) [reply runtime/error.c]: Removed

File: runtime/error.c (hunk 17 above)
Comment (KavinduZoysa) [reply runtime/error.c]: Removed

File: runtime/error.c (hunk 18 above)
Comment (KavinduZoysa) [reply runtime/error.c]: Fixed
